#!/usr/bin/env -S uv run --script --quiet
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate markdown report from ranked opportunities."""

import json
import os
import argparse
import sys
import tempfile
from datetime import datetime, timedelta, timezone


def generate(data: dict) -> str:
    now = datetime.now(timezone.utc)
    meta = data.get("metadata", {})
    ranked = data.get("ranked_opportunities", [])
    long_shots = data.get("long_shots", [])

    lines = []
    lines.append(f"# oss-veda Report -- {now.strftime('%B %d, %Y')}")
    lines.append("")
    lines.append(f"**Topic:** {meta.get('topic', 'ai')} | "
                 f"**Lookback:** {meta.get('days', 7)} days | "
                 f"**Scouts:** {meta.get('scouts_succeeded', '?')}/5 succeeded | "
                 f"**Runtime:** {meta.get('elapsed_seconds', '?')}s")
    lines.append("")
    lines.append("---")
    lines.append("")

    if not ranked:
        lines.append("No opportunities found. Try a different topic or longer lookback period.")
        return "\n".join(lines)

    # Executive summary - top 3
    lines.append("## Executive Summary -- Top 3 Picks")
    lines.append("")
    for i, opp in enumerate(ranked[:3], 1):
        repo = opp["repo"]
        issue = opp["issue"]
        lines.append(f"### {i}. [{repo['full_name']}]({repo['url']}) -- {repo['stars']} stars")
        lines.append(f"**Career Impact Score:** {opp['career_impact_score']}/100 "
                     f"(Repo: {opp['repo_score']} | Issue: {opp['issue_score']} | Fit: {opp['fit_score']})")
        lines.append(f"**Issue:** [{issue['title']}]({issue['url']})")
        labels_str = ", ".join(f"`{l}`" for l in issue.get("labels", []))
        if labels_str:
            lines.append(f"**Labels:** {labels_str}")
        if repo.get("description"):
            # Truncate on word boundary
            desc = repo["description"]
            if len(desc) > 200:
                desc = desc[:200].rsplit(" ", 1)[0] + "..."
            lines.append(f"> {desc}")
        lines.append("")

    # Full top 10 table
    lines.append("---")
    lines.append("")
    lines.append("## Top 10 Ranked Opportunities")
    lines.append("")
    lines.append("| # | Repo | Stars | Score | Issue | Labels |")
    lines.append("|---|------|-------|-------|-------|--------|")
    for i, opp in enumerate(ranked[:10], 1):
        repo = opp["repo"]
        issue = opp["issue"]
        labels = ", ".join(issue.get("labels", [])[:2])
        title_short = issue["title"][:50] + ("..." if len(issue["title"]) > 50 else "")
        lines.append(
            f"| {i} | [{repo['full_name']}]({repo['url']}) | "
            f"{repo['stars']} | {opp['career_impact_score']} | "
            f"[{title_short}]({issue['url']}) | {labels} |"
        )
    lines.append("")

    # Long shots
    if long_shots:
        lines.append("---")
        lines.append("")
        lines.append("## Long-Shot, High-Reward Picks")
        lines.append("")
        for opp in long_shots:
            repo = opp["repo"]
            issue = opp["issue"]
            lines.append(f"- **[{repo['full_name']}]({repo['url']})** ({repo['stars']} stars, "
                        f"score: {opp['career_impact_score']}) -- "
                        f"[{issue['title'][:60]}]({issue['url']})")
        lines.append("")

    # Footer
    next_scan = (now + timedelta(days=1)).strftime("%Y-%m-%d")
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by oss-veda v1.1.0 at {now.strftime('%Y-%m-%d %H:%M UTC')}*")
    lines.append(f"*Total opportunities scored: {data.get('total_scored', 0)}"
                 + (f" ({data.get('total_skipped', 0)} filtered out)" if data.get('total_skipped') else "")
                 + "*")
    lines.append(f"*Next scan recommended: {next_scan}*")

    return "\n".join(lines)


def main():
    default_input = os.path.join(tempfile.gettempdir(), "oss-veda-ranked.json")
    default_output = os.path.join(tempfile.gettempdir(), "oss-veda-report.md")

    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=default_input)
    parser.add_argument("--output", default=default_output)
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as f:
        data = json.load(f)

    report = generate(data)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(report)

    # Print to stdout for Claude to read
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print(report)


if __name__ == "__main__":
    main()
